### ISSUE TITLE
Dell RT7D20 PS/2 Keyboard may not work

### ISSUE THREAD

**Issue by jburks** [X16Community/x16-smc#31]
A report from Facebook indicates that the Dell RT7D20 keyboard is not working correctly with SMC firmware: https://www.facebook.com/groups/CommanderX16/posts/1552089275542161/

**Comment by stefan-b-jakobsson** [comment]
This suggest that that particular keyboard needs long init timeout. A first step could be to increase the current timeout of about 2.5 seconds to something like 10 seconds or even more.

https://review.coreboot.org/c/coreboot/+/486

**Comment by stefan-b-jakobsson** [comment]
We have tested in total three Dell RT7D20 keyboards after this issue was opened. They all work perfectly.

I think the Facebook user's problem remain, but we have no data to use for debugging. Maybe we can keep this issue open a bit more, but eventually we should close it.

**Comment by stople** [comment]
When testing my X16 (PR00102) with a Dell RT7D20, it failed. The problem turned out to be too weak PS2 pullups. I assume you have tested with OtterX hardware, which have different external pullup.

If applying 10k extra pullups in parallel, total pullup is strong enough.

Also, if the internal pullup is enabled all the time, the total pullup is strong enough. I have implemented this change in #41 . Without this change, the SMC will initially not engage the internal pullup.
